apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    spec:
      containers:
        - image: sulevsky/kubemetrics:0.0.3-SNAPSHOT
          name: spring-demo-container
          envFrom:
            - configMapRef:
                name: application-config-map
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
    metadata:
      labels:
        app: spring-demo
---
apiVersion: v1
kind: Service
metadata:
  name: inner-service
spec:
  selector:
    app: spring-demo
  ports:
    - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: outer-service
spec:
  type: NodePort
  selector:
    app: spring-demo
  ports:
    - port: 8080
      nodePort: 30002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-map
data:
  MESSAGE: from_config_map
